import { PLAYER_OPTIONS } from "./players";
import type { QuinielaContent } from "./schema";

const BASE = process.env.NEXT_PUBLIC_BASE_PATH ?? "";
const asset = (path: string) => `${BASE}${path}`;
const generated = (name: string) => asset(`/generated/v4/${name}.png`);
const v5 = (name: string) => asset(`/generated/v5/quiniela/${name}`);
const character = (name: string) => asset(`/characters/v3/${name}.png`);
const scene = (name: string) => v5(`scenes/${name}.png`);

export const PSG_ARSENAL_TOTAL_POINTS = 1000;

export const psgArsenal: QuinielaContent = {
  slug: "psg-arsenal",
  title: "PSG vs Arsenal",
  subtitle: "Final Champions 2026",
  eventName: "Final UEFA Champions League",
  venue: "Puskás Aréna, Budapest",
  eventDate: "2026-05-30T18:00:00+02:00",
  closesAt: "2026-05-30T17:00:00-06:00",
  status: "open",
  theme: {
    teams: {
      home: {
        id: "psg",
        label: "PSG",
        shortLabel: "PSG",
        color: "#004170",
        accent: "#1E90FF",
        crestAsset: asset("/teams/psg.svg"),
        mascotAsset: character("dino-psg"),
      },
      away: {
        id: "arsenal",
        label: "Arsenal",
        shortLabel: "ARS",
        color: "#EF0107",
        accent: "#FF4757",
        crestAsset: asset("/teams/arsenal.svg"),
        mascotAsset: character("oso-arsenal"),
      },
    },
    assets: {
      poster: v5("poster-stadium.svg"),
      trophy: generated("trophy-orejona-cartoon"),
      confetti: generated("confetti-final"),
      shareFrame: generated("share-frame-psg-arsenal"),
      celebratingMascot: generated("mascot-celebrating"),
      varSticker: v5("sticker-var-drama.svg"),
      fanSticker: v5("sticker-fan-noise.svg"),
      memeSticker: v5("sticker-meme-spotlight.svg"),
      medals: v5("ranking-medals.svg"),
    },
  },
  prizes: [
    { title: "Premio sorpresa", caption: "Para el top del ranking final" },
    { title: "Gloria social", caption: "Tarjeta compartible al terminar" },
    { title: "Modo final", caption: "Bonus por preguntas legendarias" },
  ],
  questions: [
    {
      id: "q01_campeon",
      type: "team-duel",
      category: "resultado",
      shortLabel: "CAMPEÓN",
      kicker: "Modo final",
      prompt: "¿Quién levanta la Orejona?",
      points: 120,
      badge: "legendaria",
      sceneAsset: scene("scene-champion-trophy"),
      sidekickAsset: character("mexicano-psg"),
      sidekickText: "El que elijas carga la presión de Budapest.",
    },
    {
      id: "q02_marcador_90",
      type: "score-picker",
      category: "resultado",
      shortLabel: "MARCADOR",
      kicker: "Tablero arcade",
      prompt: "Marcador al minuto 90",
      points: 120,
      helper: "No incluye tiempo extra ni penales.",
      max: 7,
      sceneAsset: scene("scene-score-match"),
      sidekickAsset: character("cebra-psg"),
      sidekickText: "Ajusta el marcador como si fuera una máquina arcade.",
    },
    {
      id: "q03_primer_gol",
      type: "team-duel",
      category: "goles",
      shortLabel: "PRIMER GOL",
      kicker: "Primer golpe",
      prompt: "¿Qué equipo anota primero?",
      points: 80,
      allowNone: true,
      noneLabel: "Ninguno en 90",
      noneCaption: "Cero drama de gol",
      noneAsset: scene("player-no-goal-gpt"),
      sceneAsset: scene("scene-first-goal"),
      sidekickAsset: character("dino-arsenal"),
      sidekickText: "El primer grito cambia toda la final.",
    },
    {
      id: "q04_primer_goleador",
      type: "player-card",
      category: "goles",
      shortLabel: "GOLEADOR",
      kicker: "Cámara lenta",
      prompt: "¿Quién marca el primer gol?",
      points: 80,
      sceneAsset: scene("scene-first-scorer-gpt"),
      sidekickAsset: character("lince-psg"),
      sidekickText: "Elige al héroe del primer rugido.",
      options: [
        PLAYER_OPTIONS.dembele,
        PLAYER_OPTIONS.kvaratskhelia,
        PLAYER_OPTIONS.saka,
        PLAYER_OPTIONS.martinelli,
        PLAYER_OPTIONS.otro,
        PLAYER_OPTIONS.ninguno,
      ],
    },
    {
      id: "q05_amarillas",
      type: "range-choice",
      category: "disciplina",
      shortLabel: "TARJETAS",
      kicker: "Árbitro protagonista",
      prompt: "¿Cuántas amarillas salen?",
      points: 70,
      sceneAsset: scene("scene-yellow-cards-gpt"),
      sidekickAsset: character("goblin-psg"),
      sidekickText: "Si la final se calienta, aquí se nota.",
      options: [
        {
          id: "0-2",
          label: "0 - 2",
          caption: "Final elegante",
          asset: scene("scene-yellow-cards-gpt"),
          color: "#2ECC71",
        },
        {
          id: "3-5",
          label: "3 - 5",
          caption: "Picante normal",
          asset: scene("scene-yellow-cards-gpt"),
          color: "#FFD93D",
        },
        {
          id: "6+",
          label: "6 o más",
          caption: "Se calienta todo",
          asset: scene("scene-yellow-cards-gpt"),
          color: "#FF4757",
        },
      ],
    },
    {
      id: "q06_penal",
      type: "yes-no",
      category: "resultado",
      shortLabel: "PENAL",
      kicker: "Silbatazo dramático",
      prompt: "¿Habrá penal?",
      points: 60,
      yesLabel: "Sí, punto penal",
      noLabel: "No, puro juego",
      yesCaption: "El estadio se congela",
      noCaption: "El VAR ni respira",
      yesAsset: scene("scene-penalty-gpt"),
      noAsset: scene("scene-tiebreaker-gpt"),
      sceneAsset: scene("scene-penalty-gpt"),
      sidekickAsset: character("oso-psg"),
      sidekickText: "Un penal en final vale doble nervio.",
    },
    {
      id: "q07_tiempo_extra",
      type: "yes-no",
      category: "resultado",
      shortLabel: "EXTRA",
      kicker: "Nervios gratis",
      prompt: "¿Se va a tiempo extra?",
      points: 70,
      yesLabel: "Sí, 120 minutos",
      noLabel: "No, se decide antes",
      yesCaption: "Piernas de gelatina",
      noCaption: "Golpe final en 90",
      yesAsset: scene("scene-extra-time-gpt"),
      noAsset: scene("scene-score-match"),
      sceneAsset: scene("scene-extra-time-gpt"),
      sidekickAsset: character("cebra-arsenal"),
      sidekickText: "La prórroga convierte la quiniela en película.",
    },
    {
      id: "q08_mvp",
      type: "player-card",
      category: "goles",
      shortLabel: "MVP",
      kicker: "Jugador de póster",
      prompt: "¿Quién será la figura del partido?",
      points: 90,
      sceneAsset: scene("scene-mvp-gpt"),
      sidekickAsset: character("mexicano-arsenal"),
      sidekickText: "Aquí va tu candidato a portada.",
      options: [
        PLAYER_OPTIONS.dembele,
        PLAYER_OPTIONS.hakimi,
        PLAYER_OPTIONS.saka,
        PLAYER_OPTIONS.rice,
        PLAYER_OPTIONS.saliba,
        PLAYER_OPTIONS.otro,
      ],
    },
    {
      id: "q09_celebracion_exagerada",
      type: "choice",
      category: "show",
      shortLabel: "FESTEJO",
      kicker: "Pregunta loca",
      prompt: "¿Quién celebrará más exageradamente?",
      points: 70,
      badge: "bonus",
      sceneAsset: scene("scene-celebration-gpt"),
      sidekickAsset: character("lince-arsenal"),
      sidekickText: "Queremos manos al cielo, vueltas y cero vergüenza.",
      options: [
        { id: "psg", label: "PSG", caption: "Baile azul", asset: character("dino-psg"), color: "#004170" },
        { id: "arsenal", label: "Arsenal", caption: "Grito rojo", asset: character("oso-arsenal"), color: "#EF0107" },
        { id: "ambos", label: "Ambos", caption: "Modo caricatura", asset: scene("scene-celebration-gpt"), color: "#FFD93D" },
        { id: "nadie", label: "Nadie", caption: "Final seria", asset: scene("player-no-goal-gpt"), color: "#6B7280" },
      ],
    },
    {
      id: "q10_baile",
      type: "yes-no",
      category: "show",
      shortLabel: "BAILE",
      kicker: "Cámara de memes",
      prompt: "¿Habrá baile de celebración?",
      points: 60,
      yesLabel: "Sí, coreografía",
      noLabel: "No, festejo sobrio",
      yesCaption: "Sale clip viral",
      noCaption: "Puño cerrado y a correr",
      yesAsset: scene("scene-dance-gpt"),
      noAsset: scene("scene-celebration-gpt"),
      sceneAsset: scene("scene-dance-gpt"),
      sidekickAsset: character("goblin-arsenal"),
      sidekickText: "Si hay baile, hay historia para compartir.",
    },
    {
      id: "q11_dt_corajes",
      type: "choice",
      category: "show",
      shortLabel: "DT",
      kicker: "Banca caliente",
      prompt: "¿Qué DT hará más corajes?",
      points: 70,
      sceneAsset: scene("scene-coach-rage-gpt"),
      sidekickAsset: character("oso-arsenal"),
      sidekickText: "La cámara de la banca nunca perdona.",
      options: [
        { id: "luis-enrique", label: "Luis Enrique", caption: "Gesto calculado", asset: scene("scene-coach-rage-gpt"), color: "#004170" },
        { id: "arteta", label: "Arteta", caption: "Brazos al cielo", asset: scene("scene-coach-rage-gpt"), color: "#EF0107" },
        { id: "ambos", label: "Ambos", caption: "Doble volcán", asset: scene("scene-celebration-gpt"), color: "#FFD93D" },
        { id: "ninguno", label: "Ninguno", caption: "Ajedrez zen", asset: scene("scene-extra-time-gpt"), color: "#2ECC71" },
      ],
    },
    {
      id: "q12_var_drama",
      type: "drama-meter",
      category: "legendaria",
      shortLabel: "VAR",
      kicker: "Pregunta legendaria",
      prompt: "Nivel de drama VAR",
      points: 70,
      badge: "legendaria",
      sceneAsset: scene("scene-var-drama-gpt"),
      sidekickAsset: character("dino-psg"),
      sidekickText: "Pantalla, silencio, todos gritando: eso cuenta.",
      options: [
        { id: "nada", label: "Nada", caption: "Ni se asoma", asset: scene("player-no-goal-gpt"), color: "#2ECC71" },
        { id: "sospechoso", label: "Sospechoso", caption: "Tres repeticiones y silencio", asset: scene("scene-var-drama-gpt"), color: "#FFD93D" },
        { id: "telenovela", label: "Telenovela total", caption: "Todos gritan a la pantalla", asset: scene("scene-var-drama-gpt"), color: "#FF4757" },
      ],
    },
    {
      id: "q13_main_character",
      type: "choice",
      category: "show",
      shortLabel: "MOMENTO",
      kicker: "Energía de protagonista",
      prompt: "¿Quién se roba la película?",
      points: 40,
      sceneAsset: scene("scene-main-character-gpt"),
      sidekickAsset: character("cebra-psg"),
      sidekickText: "No siempre gana el gol: a veces gana la escena.",
      options: [
        { id: "psg-player", label: "Jugador PSG", caption: "Pose de portada", asset: character("mexicano-psg"), color: "#004170" },
        { id: "arsenal-player", label: "Jugador Arsenal", caption: "Héroe rojo", asset: character("cebra-arsenal"), color: "#EF0107" },
        { id: "arbitro", label: "El árbitro", caption: "Plot twist", asset: scene("scene-yellow-cards-gpt"), color: "#FFD93D" },
        { id: "aficion", label: "La afición", caption: "Ruido total", asset: scene("scene-fan-noise-gpt"), color: "#1E90FF" },
      ],
    },
    {
      id: "q14_tiebreaker",
      type: "time-tiebreaker",
      category: "tiebreaker",
      shortLabel: "DESEMPATE",
      kicker: "Última moneda",
      prompt: "Minuto exacto del primer gol",
      points: 0,
      helper: "Si crees que no hay gol, marca la opción sin gol.",
      sceneAsset: scene("scene-tiebreaker-gpt"),
      sidekickAsset: character("gato-psg"),
      sidekickText: "El desempate vive en los detalles.",
    },
  ],
};
