export const SITE = {
  name: "Supergana",
  tagline: "Quinielas listas para tu marca",
  bookingCalLink: "supergana",
  bookingNamespace: "demo",
  bookingUrl: "https://cal.com/supergana",
  contactEmail: "hola@supergana.mx",
  whatsapp: "https://wa.me/521000000000",
  social: {
    instagram: "https://instagram.com/supergana",
    linkedin: "https://linkedin.com/company/supergana",
  },
} as const;

const ASSET_DIR = "v3";
const QUINIELA_ASSET_DIR = "v4";
const QUINIELA_CHARACTER_DIR = "v3";
const PREMIO_ASSET_DIR = "v5";

const BASE = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

export const asset = (path: string) =>
  `${BASE}${path.startsWith("/") ? path : `/${path}`}`;

export const gen = (name: string) => asset(`/generated/${ASSET_DIR}/${name}.png`);
export const character = (name: string) => asset(`/characters/v2/${name}.png`);

// Quiniela-specific assets generated by Codex live in fresh versioned folders
// so the landing page (v2 chars / v3 generated) is never affected.
export const quinielaAsset = (name: string) =>
  asset(`/generated/${QUINIELA_ASSET_DIR}/${name}.png`);
export const quinielaCharacter = (name: string) =>
  asset(`/characters/${QUINIELA_CHARACTER_DIR}/${name}.png`);

// Premio illustrations live in their own versioned folder so we can bump them
// independently of the landing's v3 generated set.
export const premioAsset = (name: string) =>
  asset(`/generated/${PREMIO_ASSET_DIR}/${name}.png`);

// Mundial x Rotary campaign art (Codex) lives in its own versioned folder.
const MUNDIAL_ASSET_DIR = "mundial-v1";

export const mundialAsset = (name: string) =>
  asset(`/generated/${MUNDIAL_ASSET_DIR}/${name}.png`);
