-- Seed: NFL 2026 and the Chapa pick'em programme.
--
-- GENERATED by scripts/pickem-schedule-sql.mjs from scripts/data/nfl-2026-schedule.json.
-- Re-generate rather than edit; the script refuses to print a schedule that
-- does not satisfy 272 = 32 teams × 17 games ÷ 2 with every team at exactly 17.
--
-- 272 games across 18 weeks. 24 carry no network yet
-- (ESPN returns "?"), which is normal: the league assigns those broadcasts late.
--
-- Kickoffs are UTC. They are read in America/Ciudad_Juarez, which is Mountain
-- time synced to El Paso rather than Central like the rest of Chihuahua, and
-- daylight saving ends 1 November 2026 — mid-season. Week 1 shows MDT, week 9
-- onward MST. Formatting with Intl in that zone gets this right; subtracting a
-- fixed offset is wrong from week 9 on, by exactly the hour somebody needs to
-- not miss their lock.

-- ===========================================================================
-- The season
-- ===========================================================================

insert into public.sport_seasons (league, year, weeks)
values ('nfl', 2026, 18)
on conflict (league, year) do update set weeks = excluded.weeks;

insert into public.sport_games (season_id, week, away, home, kickoff_at, network, venue_note)
select s.id, v.week, v.away, v.home, v.kickoff_at, v.network, v.venue_note
from public.sport_seasons s,
(values
  (1, 'NE', 'SEA', '2026-09-10T00:20:00.000Z'::timestamptz, 'NBC', 'Kickoff de temporada'),
  (1, 'SF', 'LAR', '2026-09-11T00:35:00.000Z'::timestamptz, 'Netflix', 'Melbourne, Australia'),
  (1, 'TB', 'CIN', '2026-09-13T17:00:00.000Z'::timestamptz, 'FOX', null),
  (1, 'NO', 'DET', '2026-09-13T17:00:00.000Z'::timestamptz, 'FOX', null),
  (1, 'NYJ', 'TEN', '2026-09-13T17:00:00.000Z'::timestamptz, 'CBS', null),
  (1, 'BAL', 'IND', '2026-09-13T17:00:00.000Z'::timestamptz, 'CBS', null),
  (1, 'ATL', 'PIT', '2026-09-13T17:00:00.000Z'::timestamptz, 'FOX', null),
  (1, 'CHI', 'CAR', '2026-09-13T17:00:00.000Z'::timestamptz, 'FOX', null),
  (1, 'CLE', 'JAX', '2026-09-13T17:00:00.000Z'::timestamptz, 'CBS', null),
  (1, 'BUF', 'HOU', '2026-09-13T17:00:00.000Z'::timestamptz, 'CBS', null),
  (1, 'MIA', 'LV', '2026-09-13T20:25:00.000Z'::timestamptz, 'FOX', null),
  (1, 'GB', 'MIN', '2026-09-13T20:25:00.000Z'::timestamptz, 'CBS', null),
  (1, 'WSH', 'PHI', '2026-09-13T20:25:00.000Z'::timestamptz, 'FOX', null),
  (1, 'ARI', 'LAC', '2026-09-13T20:25:00.000Z'::timestamptz, 'CBS', null),
  (1, 'DAL', 'NYG', '2026-09-14T00:20:00.000Z'::timestamptz, 'NBC', 'Sunday Night'),
  (1, 'DEN', 'KC', '2026-09-15T00:15:00.000Z'::timestamptz, 'ESPN', 'Monday Night'),
  (2, 'DET', 'BUF', '2026-09-18T00:15:00.000Z'::timestamptz, 'Prime Video', 'Thursday Night'),
  (2, 'CAR', 'ATL', '2026-09-20T17:00:00.000Z'::timestamptz, 'FOX', null),
  (2, 'MIN', 'CHI', '2026-09-20T17:00:00.000Z'::timestamptz, 'FOX', null),
  (2, 'PHI', 'TEN', '2026-09-20T17:00:00.000Z'::timestamptz, 'FOX', null),
  (2, 'PIT', 'NE', '2026-09-20T17:00:00.000Z'::timestamptz, 'CBS', null),
  (2, 'GB', 'NYJ', '2026-09-20T17:00:00.000Z'::timestamptz, 'FOX', null),
  (2, 'CLE', 'TB', '2026-09-20T17:00:00.000Z'::timestamptz, 'CBS', null),
  (2, 'NO', 'BAL', '2026-09-20T17:00:00.000Z'::timestamptz, 'CBS', null),
  (2, 'CIN', 'HOU', '2026-09-20T17:00:00.000Z'::timestamptz, 'CBS', null),
  (2, 'JAX', 'DEN', '2026-09-20T20:05:00.000Z'::timestamptz, 'CBS', null),
  (2, 'LV', 'LAC', '2026-09-20T20:05:00.000Z'::timestamptz, 'CBS', null),
  (2, 'WSH', 'DAL', '2026-09-20T20:25:00.000Z'::timestamptz, 'FOX', null),
  (2, 'SEA', 'ARI', '2026-09-20T20:25:00.000Z'::timestamptz, 'FOX', null),
  (2, 'MIA', 'SF', '2026-09-20T20:25:00.000Z'::timestamptz, 'FOX', null),
  (2, 'IND', 'KC', '2026-09-21T00:20:00.000Z'::timestamptz, 'NBC', 'Sunday Night'),
  (2, 'NYG', 'LAR', '2026-09-22T00:15:00.000Z'::timestamptz, 'ESPN', 'Monday Night'),
  (3, 'ATL', 'GB', '2026-09-25T00:15:00.000Z'::timestamptz, 'Prime Video', 'Thursday Night'),
  (3, 'LAC', 'BUF', '2026-09-27T17:00:00.000Z'::timestamptz, 'FOX', null),
  (3, 'CAR', 'CLE', '2026-09-27T17:00:00.000Z'::timestamptz, 'FOX', null),
  (3, 'NYJ', 'DET', '2026-09-27T17:00:00.000Z'::timestamptz, 'FOX', null),
  (3, 'HOU', 'IND', '2026-09-27T17:00:00.000Z'::timestamptz, 'CBS', null),
  (3, 'KC', 'MIA', '2026-09-27T17:00:00.000Z'::timestamptz, 'CBS', null),
  (3, 'TEN', 'NYG', '2026-09-27T17:00:00.000Z'::timestamptz, 'CBS', null),
  (3, 'CIN', 'PIT', '2026-09-27T17:00:00.000Z'::timestamptz, 'CBS', null),
  (3, 'SEA', 'WSH', '2026-09-27T17:00:00.000Z'::timestamptz, 'FOX', null),
  (3, 'NE', 'JAX', '2026-09-27T17:00:00.000Z'::timestamptz, 'CBS', null),
  (3, 'ARI', 'SF', '2026-09-27T20:05:00.000Z'::timestamptz, 'FOX', null),
  (3, 'MIN', 'TB', '2026-09-27T20:05:00.000Z'::timestamptz, 'FOX', null),
  (3, 'BAL', 'DAL', '2026-09-27T20:25:00.000Z'::timestamptz, 'CBS', 'Rio De Janeiro, Brazil'),
  (3, 'LV', 'NO', '2026-09-27T20:25:00.000Z'::timestamptz, 'CBS', null),
  (3, 'LAR', 'DEN', '2026-09-28T00:20:00.000Z'::timestamptz, 'NBC', 'Sunday Night'),
  (3, 'PHI', 'CHI', '2026-09-29T00:15:00.000Z'::timestamptz, 'ESPN', 'Monday Night'),
  (4, 'PIT', 'CLE', '2026-10-02T00:15:00.000Z'::timestamptz, 'Prime Video', 'Thursday Night'),
  (4, 'IND', 'WSH', '2026-10-04T13:30:00.000Z'::timestamptz, 'NFL Net', 'London, England'),
  (4, 'NE', 'BUF', '2026-10-04T17:00:00.000Z'::timestamptz, 'CBS', null),
  (4, 'NYJ', 'CHI', '2026-10-04T17:00:00.000Z'::timestamptz, 'FOX', null),
  (4, 'JAX', 'CIN', '2026-10-04T17:00:00.000Z'::timestamptz, 'CBS', null),
  (4, 'ARI', 'NYG', '2026-10-04T17:00:00.000Z'::timestamptz, 'CBS', null),
  (4, 'LAR', 'PHI', '2026-10-04T17:00:00.000Z'::timestamptz, 'FOX', null),
  (4, 'GB', 'TB', '2026-10-04T17:00:00.000Z'::timestamptz, 'FOX', null),
  (4, 'TEN', 'BAL', '2026-10-04T17:00:00.000Z'::timestamptz, 'CBS', null),
  (4, 'DAL', 'HOU', '2026-10-04T17:00:00.000Z'::timestamptz, 'FOX', null),
  (4, 'MIA', 'MIN', '2026-10-04T20:05:00.000Z'::timestamptz, 'FOX', null),
  (4, 'KC', 'LV', '2026-10-04T20:25:00.000Z'::timestamptz, 'CBS', null),
  (4, 'DEN', 'SF', '2026-10-04T20:25:00.000Z'::timestamptz, 'CBS', null),
  (4, 'LAC', 'SEA', '2026-10-04T20:25:00.000Z'::timestamptz, 'CBS', null),
  (4, 'DET', 'CAR', '2026-10-05T00:20:00.000Z'::timestamptz, 'NBC', 'Sunday Night'),
  (4, 'ATL', 'NO', '2026-10-06T00:15:00.000Z'::timestamptz, 'ESPN', 'Monday Night'),
  (5, 'TB', 'DAL', '2026-10-09T00:15:00.000Z'::timestamptz, 'Prime Video', 'Thursday Night'),
  (5, 'PHI', 'JAX', '2026-10-11T13:30:00.000Z'::timestamptz, 'NFL Net', 'London, England'),
  (5, 'HOU', 'TEN', '2026-10-11T17:00:00.000Z'::timestamptz, 'CBS', null),
  (5, 'CIN', 'MIA', '2026-10-11T17:00:00.000Z'::timestamptz, 'FOX', null),
  (5, 'LV', 'NE', '2026-10-11T17:00:00.000Z'::timestamptz, 'CBS', null),
  (5, 'MIN', 'NO', '2026-10-11T17:00:00.000Z'::timestamptz, 'FOX', null),
  (5, 'CLE', 'NYJ', '2026-10-11T17:00:00.000Z'::timestamptz, 'CBS', null),
  (5, 'IND', 'PIT', '2026-10-11T17:00:00.000Z'::timestamptz, 'CBS', null),
  (5, 'NYG', 'WSH', '2026-10-11T17:00:00.000Z'::timestamptz, 'FOX', null),
  (5, 'DEN', 'LAC', '2026-10-11T20:05:00.000Z'::timestamptz, 'CBS', null),
  (5, 'CHI', 'GB', '2026-10-11T20:25:00.000Z'::timestamptz, 'FOX', null),
  (5, 'DET', 'ARI', '2026-10-11T20:25:00.000Z'::timestamptz, 'FOX', null),
  (5, 'SF', 'SEA', '2026-10-11T20:25:00.000Z'::timestamptz, 'FOX', null),
  (5, 'BAL', 'ATL', '2026-10-12T00:20:00.000Z'::timestamptz, 'NBC', 'Sunday Night'),
  (5, 'BUF', 'LAR', '2026-10-13T00:15:00.000Z'::timestamptz, 'ESPN', 'Monday Night'),
  (6, 'SEA', 'DEN', '2026-10-16T00:15:00.000Z'::timestamptz, 'Prime Video', 'Thursday Night'),
  (6, 'HOU', 'JAX', '2026-10-18T13:30:00.000Z'::timestamptz, 'NFL Net', 'London, England'),
  (6, 'CHI', 'ATL', '2026-10-18T17:00:00.000Z'::timestamptz, 'FOX', null),
  (6, 'BAL', 'CLE', '2026-10-18T17:00:00.000Z'::timestamptz, 'FOX', null),
  (6, 'TEN', 'IND', '2026-10-18T17:00:00.000Z'::timestamptz, 'FOX', null),
  (6, 'NYJ', 'NE', '2026-10-18T17:00:00.000Z'::timestamptz, 'CBS', null),
  (6, 'NO', 'NYG', '2026-10-18T17:00:00.000Z'::timestamptz, 'FOX', null),
  (6, 'CAR', 'PHI', '2026-10-18T17:00:00.000Z'::timestamptz, 'CBS', null),
  (6, 'PIT', 'TB', '2026-10-18T17:00:00.000Z'::timestamptz, 'CBS', null),
  (6, 'ARI', 'LAR', '2026-10-18T20:05:00.000Z'::timestamptz, 'FOX', null),
  (6, 'LAC', 'KC', '2026-10-18T20:25:00.000Z'::timestamptz, 'CBS', null),
  (6, 'BUF', 'LV', '2026-10-18T20:25:00.000Z'::timestamptz, 'CBS', null),
  (6, 'DAL', 'GB', '2026-10-19T00:20:00.000Z'::timestamptz, 'NBC', 'Sunday Night'),
  (6, 'WSH', 'SF', '2026-10-20T00:15:00.000Z'::timestamptz, 'ESPN', 'Monday Night'),
  (7, 'NE', 'CHI', '2026-10-23T00:15:00.000Z'::timestamptz, 'Prime Video', 'Thursday Night'),
  (7, 'PIT', 'NO', '2026-10-25T13:30:00.000Z'::timestamptz, 'NFL Net', 'Saint-Denis, France'),
  (7, 'SF', 'ATL', '2026-10-25T17:00:00.000Z'::timestamptz, 'FOX', null),
  (7, 'CLE', 'TEN', '2026-10-25T17:00:00.000Z'::timestamptz, 'CBS', null),
  (7, 'IND', 'MIN', '2026-10-25T17:00:00.000Z'::timestamptz, 'CBS', null),
  (7, 'MIA', 'NYJ', '2026-10-25T17:00:00.000Z'::timestamptz, 'CBS', null),
  (7, 'TB', 'CAR', '2026-10-25T17:00:00.000Z'::timestamptz, 'FOX', null),
  (7, 'CIN', 'BAL', '2026-10-25T17:00:00.000Z'::timestamptz, 'CBS', null),
  (7, 'NYG', 'HOU', '2026-10-25T17:00:00.000Z'::timestamptz, 'FOX', null),
  (7, 'DEN', 'ARI', '2026-10-25T20:05:00.000Z'::timestamptz, 'CBS', null),
  (7, 'GB', 'DET', '2026-10-25T20:25:00.000Z'::timestamptz, 'FOX', null),
  (7, 'LAR', 'LV', '2026-10-25T20:25:00.000Z'::timestamptz, 'FOX', null),
  (7, 'KC', 'SEA', '2026-10-26T00:20:00.000Z'::timestamptz, 'NBC', 'Sunday Night'),
  (7, 'DAL', 'PHI', '2026-10-27T00:15:00.000Z'::timestamptz, 'ESPN', 'Monday Night'),
  (8, 'CAR', 'GB', '2026-10-30T00:15:00.000Z'::timestamptz, 'Prime Video', 'Thursday Night'),
  (8, 'BAL', 'BUF', '2026-11-01T18:00:00.000Z'::timestamptz, 'CBS', null),
  (8, 'TEN', 'CIN', '2026-11-01T18:00:00.000Z'::timestamptz, 'CBS', null),
  (8, 'ARI', 'DAL', '2026-11-01T18:00:00.000Z'::timestamptz, 'FOX', null),
  (8, 'MIN', 'DET', '2026-11-01T18:00:00.000Z'::timestamptz, 'FOX', null),
  (8, 'LV', 'NYJ', '2026-11-01T18:00:00.000Z'::timestamptz, 'FOX', null),
  (8, 'CLE', 'PIT', '2026-11-01T18:00:00.000Z'::timestamptz, 'CBS', null),
  (8, 'ATL', 'TB', '2026-11-01T18:00:00.000Z'::timestamptz, 'FOX', null),
  (8, 'IND', 'JAX', '2026-11-01T18:00:00.000Z'::timestamptz, 'CBS', null),
  (8, 'LAC', 'LAR', '2026-11-01T21:05:00.000Z'::timestamptz, 'FOX', null),
  (8, 'KC', 'DEN', '2026-11-01T21:25:00.000Z'::timestamptz, 'CBS', null),
  (8, 'NE', 'MIA', '2026-11-01T21:25:00.000Z'::timestamptz, 'CBS', null),
  (8, 'PHI', 'WSH', '2026-11-02T01:20:00.000Z'::timestamptz, 'NBC', 'Sunday Night'),
  (8, 'CHI', 'SEA', '2026-11-03T01:15:00.000Z'::timestamptz, 'ESPN', 'Monday Night'),
  (9, 'JAX', 'BAL', '2026-11-06T01:15:00.000Z'::timestamptz, 'Prime Video', 'Thursday Night'),
  (9, 'CIN', 'ATL', '2026-11-08T14:30:00.000Z'::timestamptz, 'NFL Net', 'Madrid, Spain'),
  (9, 'DAL', 'IND', '2026-11-08T18:00:00.000Z'::timestamptz, 'FOX', null),
  (9, 'NYJ', 'KC', '2026-11-08T18:00:00.000Z'::timestamptz, 'CBS', null),
  (9, 'DET', 'MIA', '2026-11-08T18:00:00.000Z'::timestamptz, 'FOX', null),
  (9, 'CLE', 'NO', '2026-11-08T18:00:00.000Z'::timestamptz, 'CBS', null),
  (9, 'NYG', 'PHI', '2026-11-08T18:00:00.000Z'::timestamptz, 'FOX', null),
  (9, 'LAR', 'WSH', '2026-11-08T18:00:00.000Z'::timestamptz, 'FOX', null),
  (9, 'DEN', 'CAR', '2026-11-08T18:00:00.000Z'::timestamptz, 'CBS', null),
  (9, 'HOU', 'LAC', '2026-11-08T21:05:00.000Z'::timestamptz, 'CBS', null),
  (9, 'LV', 'SF', '2026-11-08T21:05:00.000Z'::timestamptz, 'CBS', null),
  (9, 'GB', 'NE', '2026-11-08T21:25:00.000Z'::timestamptz, 'FOX', null),
  (9, 'ARI', 'SEA', '2026-11-08T21:25:00.000Z'::timestamptz, 'FOX', null),
  (9, 'TB', 'CHI', '2026-11-09T01:20:00.000Z'::timestamptz, 'NBC', 'Sunday Night'),
  (9, 'BUF', 'MIN', '2026-11-10T01:15:00.000Z'::timestamptz, 'ESPN', 'Monday Night'),
  (10, 'WSH', 'NYG', '2026-11-13T01:15:00.000Z'::timestamptz, 'Prime Video', 'Thursday Night'),
  (10, 'NE', 'DET', '2026-11-15T14:30:00.000Z'::timestamptz, 'FOX', 'Munich, Germany'),
  (10, 'KC', 'ATL', '2026-11-15T18:00:00.000Z'::timestamptz, 'CBS', null),
  (10, 'HOU', 'CLE', '2026-11-15T18:00:00.000Z'::timestamptz, 'FOX', null),
  (10, 'MIN', 'GB', '2026-11-15T18:00:00.000Z'::timestamptz, 'FOX', null),
  (10, 'JAX', 'TEN', '2026-11-15T18:00:00.000Z'::timestamptz, 'FOX', null),
  (10, 'MIA', 'IND', '2026-11-15T18:00:00.000Z'::timestamptz, 'CBS', null),
  (10, 'CAR', 'NO', '2026-11-15T18:00:00.000Z'::timestamptz, 'FOX', null),
  (10, 'BUF', 'NYJ', '2026-11-15T18:00:00.000Z'::timestamptz, 'CBS', null),
  (10, 'SEA', 'LV', '2026-11-15T21:05:00.000Z'::timestamptz, 'CBS', null),
  (10, 'LAR', 'ARI', '2026-11-15T21:05:00.000Z'::timestamptz, 'CBS', null),
  (10, 'SF', 'DAL', '2026-11-15T21:25:00.000Z'::timestamptz, 'FOX', null),
  (10, 'PIT', 'CIN', '2026-11-16T01:20:00.000Z'::timestamptz, 'NBC', 'Sunday Night'),
  (10, 'LAC', 'BAL', '2026-11-17T01:15:00.000Z'::timestamptz, 'ESPN', 'Monday Night'),
  (11, 'IND', 'HOU', '2026-11-20T01:15:00.000Z'::timestamptz, 'Prime Video', 'Thursday Night'),
  (11, 'MIA', 'BUF', '2026-11-22T18:00:00.000Z'::timestamptz, 'FOX', null),
  (11, 'NO', 'CHI', '2026-11-22T18:00:00.000Z'::timestamptz, 'FOX', null),
  (11, 'TEN', 'DAL', '2026-11-22T18:00:00.000Z'::timestamptz, 'FOX', null),
  (11, 'TB', 'DET', '2026-11-22T18:00:00.000Z'::timestamptz, 'CBS', null),
  (11, 'ARI', 'KC', '2026-11-22T18:00:00.000Z'::timestamptz, 'CBS', null),
  (11, 'JAX', 'NYG', '2026-11-22T18:00:00.000Z'::timestamptz, 'CBS', null),
  (11, 'BAL', 'CAR', '2026-11-22T18:00:00.000Z'::timestamptz, 'FOX', null),
  (11, 'NYJ', 'LAC', '2026-11-22T21:05:00.000Z'::timestamptz, 'FOX', null),
  (11, 'LV', 'DEN', '2026-11-22T21:25:00.000Z'::timestamptz, 'CBS', null),
  (11, 'PIT', 'PHI', '2026-11-22T21:25:00.000Z'::timestamptz, 'CBS', null),
  (11, 'MIN', 'SF', '2026-11-23T01:20:00.000Z'::timestamptz, 'NBC', 'Mexico City, Mexico'),
  (11, 'CIN', 'WSH', '2026-11-24T01:15:00.000Z'::timestamptz, 'ESPN', 'Monday Night'),
  (12, 'GB', 'LAR', '2026-11-26T01:00:00.000Z'::timestamptz, 'Netflix', 'Partido de miércoles'),
  (12, 'CHI', 'DET', '2026-11-26T18:00:00.000Z'::timestamptz, 'CBS', 'Thanksgiving'),
  (12, 'PHI', 'DAL', '2026-11-26T21:30:00.000Z'::timestamptz, 'FOX', 'Thanksgiving'),
  (12, 'KC', 'BUF', '2026-11-27T01:20:00.000Z'::timestamptz, 'NBC', 'Thursday Night'),
  (12, 'DEN', 'PIT', '2026-11-27T20:00:00.000Z'::timestamptz, 'Prime Video', null),
  (12, 'NO', 'CIN', '2026-11-29T18:00:00.000Z'::timestamptz, 'CBS', null),
  (12, 'LV', 'CLE', '2026-11-29T18:00:00.000Z'::timestamptz, 'FOX', null),
  (12, 'NYG', 'IND', '2026-11-29T18:00:00.000Z'::timestamptz, 'FOX', null),
  (12, 'NYJ', 'MIA', '2026-11-29T18:00:00.000Z'::timestamptz, 'CBS', null),
  (12, 'ATL', 'MIN', '2026-11-29T18:00:00.000Z'::timestamptz, 'FOX', null),
  (12, 'BAL', 'HOU', '2026-11-29T18:00:00.000Z'::timestamptz, 'CBS', null),
  (12, 'TEN', 'JAX', '2026-11-29T21:05:00.000Z'::timestamptz, 'CBS', null),
  (12, 'WSH', 'ARI', '2026-11-29T21:25:00.000Z'::timestamptz, 'FOX', null),
  (12, 'SEA', 'SF', '2026-11-29T21:25:00.000Z'::timestamptz, 'FOX', null),
  (12, 'NE', 'LAC', '2026-11-30T01:20:00.000Z'::timestamptz, 'NBC', 'Sunday Night'),
  (12, 'CAR', 'TB', '2026-12-01T01:15:00.000Z'::timestamptz, 'ESPN', 'Monday Night'),
  (13, 'KC', 'LAR', '2026-12-04T01:15:00.000Z'::timestamptz, 'Prime Video', 'Thursday Night'),
  (13, 'DET', 'ATL', '2026-12-06T18:00:00.000Z'::timestamptz, 'CBS', null),
  (13, 'JAX', 'CHI', '2026-12-06T18:00:00.000Z'::timestamptz, 'FOX', null),
  (13, 'CIN', 'CLE', '2026-12-06T18:00:00.000Z'::timestamptz, 'CBS', null),
  (13, 'WSH', 'TEN', '2026-12-06T18:00:00.000Z'::timestamptz, 'CBS', null),
  (13, 'GB', 'NO', '2026-12-06T18:00:00.000Z'::timestamptz, 'FOX', null),
  (13, 'SF', 'NYG', '2026-12-06T18:00:00.000Z'::timestamptz, 'FOX', null),
  (13, 'LAC', 'TB', '2026-12-06T18:00:00.000Z'::timestamptz, 'CBS', null),
  (13, 'MIA', 'DEN', '2026-12-06T21:05:00.000Z'::timestamptz, 'FOX', null),
  (13, 'PHI', 'ARI', '2026-12-06T21:05:00.000Z'::timestamptz, 'FOX', null),
  (13, 'CAR', 'MIN', '2026-12-06T21:25:00.000Z'::timestamptz, 'CBS', null),
  (13, 'BUF', 'NE', '2026-12-06T21:25:00.000Z'::timestamptz, 'CBS', null),
  (13, 'HOU', 'PIT', '2026-12-07T01:20:00.000Z'::timestamptz, 'NBC', 'Sunday Night'),
  (13, 'DAL', 'SEA', '2026-12-08T01:15:00.000Z'::timestamptz, 'ESPN', 'Monday Night'),
  (14, 'MIN', 'NE', '2026-12-11T01:15:00.000Z'::timestamptz, 'Prime Video', 'Thursday Night'),
  (14, 'ATL', 'CLE', '2026-12-13T18:00:00.000Z'::timestamptz, 'CBS', null),
  (14, 'TEN', 'DET', '2026-12-13T18:00:00.000Z'::timestamptz, 'FOX', null),
  (14, 'CHI', 'MIA', '2026-12-13T18:00:00.000Z'::timestamptz, 'CBS', null),
  (14, 'DEN', 'NYJ', '2026-12-13T18:00:00.000Z'::timestamptz, 'CBS', null),
  (14, 'IND', 'PHI', '2026-12-13T18:00:00.000Z'::timestamptz, 'FOX', null),
  (14, 'HOU', 'WSH', '2026-12-13T18:00:00.000Z'::timestamptz, 'CBS', null),
  (14, 'NO', 'CAR', '2026-12-13T18:00:00.000Z'::timestamptz, 'CBS', null),
  (14, 'TB', 'BAL', '2026-12-13T18:00:00.000Z'::timestamptz, 'FOX', null),
  (14, 'LAC', 'LV', '2026-12-13T21:05:00.000Z'::timestamptz, 'CBS', null),
  (14, 'KC', 'CIN', '2026-12-13T21:25:00.000Z'::timestamptz, 'FOX', null),
  (14, 'LAR', 'SF', '2026-12-13T21:25:00.000Z'::timestamptz, 'FOX', null),
  (14, 'NYG', 'SEA', '2026-12-13T21:25:00.000Z'::timestamptz, 'FOX', null),
  (14, 'BUF', 'GB', '2026-12-14T01:20:00.000Z'::timestamptz, 'NBC', 'Sunday Night'),
  (14, 'PIT', 'JAX', '2026-12-15T01:15:00.000Z'::timestamptz, 'ESPN', 'Monday Night'),
  (15, 'SF', 'LAC', '2026-12-18T01:15:00.000Z'::timestamptz, 'Prime Video', 'Thursday Night'),
  (15, 'SEA', 'PHI', '2026-12-19T22:00:00.000Z'::timestamptz, 'FOX', 'Sábado'),
  (15, 'CHI', 'BUF', '2026-12-20T01:20:00.000Z'::timestamptz, 'CBS', 'Sábado'),
  (15, 'MIA', 'GB', '2026-12-20T18:00:00.000Z'::timestamptz, 'FOX', null),
  (15, 'IND', 'TEN', '2026-12-20T18:00:00.000Z'::timestamptz, 'CBS', null),
  (15, 'CLE', 'NYG', '2026-12-20T18:00:00.000Z'::timestamptz, 'CBS', null),
  (15, 'BAL', 'PIT', '2026-12-20T18:00:00.000Z'::timestamptz, 'CBS', null),
  (15, 'NO', 'TB', '2026-12-20T18:00:00.000Z'::timestamptz, 'FOX', null),
  (15, 'ATL', 'WSH', '2026-12-20T18:00:00.000Z'::timestamptz, 'FOX', null),
  (15, 'CIN', 'CAR', '2026-12-20T18:00:00.000Z'::timestamptz, 'FOX', null),
  (15, 'JAX', 'HOU', '2026-12-20T18:00:00.000Z'::timestamptz, 'CBS', null),
  (15, 'NYJ', 'ARI', '2026-12-20T21:05:00.000Z'::timestamptz, 'FOX', null),
  (15, 'DEN', 'LV', '2026-12-20T21:25:00.000Z'::timestamptz, 'CBS', null),
  (15, 'DAL', 'LAR', '2026-12-20T21:25:00.000Z'::timestamptz, 'CBS', null),
  (15, 'DET', 'MIN', '2026-12-21T01:20:00.000Z'::timestamptz, 'NBC', 'Sunday Night'),
  (15, 'NE', 'KC', '2026-12-22T01:15:00.000Z'::timestamptz, 'ESPN', 'Monday Night'),
  (16, 'HOU', 'PHI', '2026-12-25T01:15:00.000Z'::timestamptz, 'Prime Video', 'Thursday Night'),
  (16, 'GB', 'CHI', '2026-12-25T18:00:00.000Z'::timestamptz, 'Netflix', null),
  (16, 'BUF', 'DEN', '2026-12-25T21:30:00.000Z'::timestamptz, 'Netflix', null),
  (16, 'LAR', 'SEA', '2026-12-26T01:15:00.000Z'::timestamptz, 'FOX', null),
  (16, 'TB', 'ATL', '2026-12-27T05:00:00.000Z'::timestamptz, null, 'Sábado'),
  (16, 'CIN', 'IND', '2026-12-27T05:00:00.000Z'::timestamptz, null, 'Sábado'),
  (16, 'WSH', 'MIN', '2026-12-27T05:00:00.000Z'::timestamptz, null, 'Sábado'),
  (16, 'CAR', 'PIT', '2026-12-27T05:00:00.000Z'::timestamptz, null, 'Sábado'),
  (16, 'LAC', 'MIA', '2026-12-27T18:00:00.000Z'::timestamptz, 'FOX', null),
  (16, 'ARI', 'NO', '2026-12-27T18:00:00.000Z'::timestamptz, 'FOX', null),
  (16, 'NE', 'NYJ', '2026-12-27T18:00:00.000Z'::timestamptz, 'CBS', null),
  (16, 'CLE', 'BAL', '2026-12-27T18:00:00.000Z'::timestamptz, 'CBS', null),
  (16, 'TEN', 'LV', '2026-12-27T21:05:00.000Z'::timestamptz, 'FOX', null),
  (16, 'SF', 'KC', '2026-12-27T21:25:00.000Z'::timestamptz, 'CBS', null),
  (16, 'JAX', 'DAL', '2026-12-28T01:20:00.000Z'::timestamptz, 'NBC', 'Sunday Night'),
  (16, 'NYG', 'DET', '2026-12-29T01:15:00.000Z'::timestamptz, 'ESPN', 'Monday Night'),
  (17, 'BAL', 'CIN', '2027-01-01T01:15:00.000Z'::timestamptz, 'Prime Video', 'Thursday Night'),
  (17, 'DEN', 'NE', '2027-01-03T05:00:00.000Z'::timestamptz, null, 'Sábado'),
  (17, 'KC', 'LAC', '2027-01-03T05:00:00.000Z'::timestamptz, null, 'Sábado'),
  (17, 'LAR', 'TB', '2027-01-03T05:00:00.000Z'::timestamptz, null, 'Sábado'),
  (17, 'WSH', 'JAX', '2027-01-03T05:00:00.000Z'::timestamptz, null, 'Sábado'),
  (17, 'NO', 'ATL', '2027-01-03T18:00:00.000Z'::timestamptz, 'FOX', null),
  (17, 'IND', 'CLE', '2027-01-03T18:00:00.000Z'::timestamptz, 'FOX', null),
  (17, 'NYG', 'DAL', '2027-01-03T18:00:00.000Z'::timestamptz, 'FOX', null),
  (17, 'PIT', 'TEN', '2027-01-03T18:00:00.000Z'::timestamptz, 'CBS', null),
  (17, 'BUF', 'MIA', '2027-01-03T18:00:00.000Z'::timestamptz, 'CBS', null),
  (17, 'MIN', 'NYJ', '2027-01-03T18:00:00.000Z'::timestamptz, 'CBS', null),
  (17, 'SEA', 'CAR', '2027-01-03T18:00:00.000Z'::timestamptz, 'FOX', null),
  (17, 'LV', 'ARI', '2027-01-03T21:05:00.000Z'::timestamptz, 'CBS', null),
  (17, 'DET', 'CHI', '2027-01-03T21:25:00.000Z'::timestamptz, 'FOX', null),
  (17, 'PHI', 'SF', '2027-01-04T01:20:00.000Z'::timestamptz, 'NBC', 'Sunday Night'),
  (17, 'HOU', 'GB', '2027-01-05T01:15:00.000Z'::timestamptz, 'ESPN', 'Monday Night'),
  (18, 'NYJ', 'BUF', '2027-01-10T05:00:00.000Z'::timestamptz, null, 'Sábado'),
  (18, 'CLE', 'CIN', '2027-01-10T05:00:00.000Z'::timestamptz, null, 'Sábado'),
  (18, 'LAC', 'DEN', '2027-01-10T05:00:00.000Z'::timestamptz, null, 'Sábado'),
  (18, 'DET', 'GB', '2027-01-10T05:00:00.000Z'::timestamptz, null, 'Sábado'),
  (18, 'JAX', 'IND', '2027-01-10T05:00:00.000Z'::timestamptz, null, 'Sábado'),
  (18, 'LV', 'KC', '2027-01-10T05:00:00.000Z'::timestamptz, null, 'Sábado'),
  (18, 'SEA', 'LAR', '2027-01-10T05:00:00.000Z'::timestamptz, null, 'Sábado'),
  (18, 'CHI', 'MIN', '2027-01-10T05:00:00.000Z'::timestamptz, null, 'Sábado'),
  (18, 'MIA', 'NE', '2027-01-10T05:00:00.000Z'::timestamptz, null, 'Sábado'),
  (18, 'TB', 'NO', '2027-01-10T05:00:00.000Z'::timestamptz, null, 'Sábado'),
  (18, 'PHI', 'NYG', '2027-01-10T05:00:00.000Z'::timestamptz, null, 'Sábado'),
  (18, 'SF', 'ARI', '2027-01-10T05:00:00.000Z'::timestamptz, null, 'Sábado'),
  (18, 'DAL', 'WSH', '2027-01-10T05:00:00.000Z'::timestamptz, null, 'Sábado'),
  (18, 'ATL', 'CAR', '2027-01-10T05:00:00.000Z'::timestamptz, null, 'Sábado'),
  (18, 'PIT', 'BAL', '2027-01-10T05:00:00.000Z'::timestamptz, null, 'Sábado'),
  (18, 'TEN', 'HOU', '2027-01-10T05:00:00.000Z'::timestamptz, null, 'Sábado')
) as v(week, away, home, kickoff_at, network, venue_note)
where s.league = 'nfl' and s.year = 2026
on conflict (season_id, week, away, home) do update
  set kickoff_at = excluded.kickoff_at,
      network    = coalesce(excluded.network, public.sport_games.network),
      venue_note = excluded.venue_note;

-- The check that matters, run again against what actually landed. A seed that
-- half-applied is worse than one that failed.
do $$
declare v_count int;
begin
  select count(*) into v_count
  from public.sport_games g
  join public.sport_seasons s on s.id = g.season_id
  where s.league = 'nfl' and s.year = 2026;
  if v_count <> 272 then
    raise exception 'sport_games has % rows for nfl 2026, expected 272', v_count;
  end if;
end $$;

-- ===========================================================================
-- Chapa
-- ===========================================================================
--
-- Copper and charcoal sampled from the files the client delivered. Only the
-- brand pair is themeable — action stays Supergana yellow, because the buttons
-- are the product's vocabulary and a tenant repainting them would be a tenant
-- forking the product (lib/tickets/theme.ts).
--
-- brand_ink is a separate value rather than a darkened brand: #D0765E is 2.6:1
-- on cream, which fails even the large-text bar, so body copy needs its own
-- darker tone. Guessing "darken until it passes" produces mud.

insert into public.organizations (slug, name, theme)
values (
  'chapa',
  'Chapa Carnes & Cantina',
  jsonb_build_object(
    'logo_url', '/brands/chapa/chapa-emblema-256.png',
    'logo_alt', 'Chapa Carnes & Cantina',
    'brand', '#d0765e',
    'brand_ink', '#8c3f2b',
    'powered_by', true
  )
)
on conflict (slug) do update
  set name = excluded.name, theme = excluded.theme;

-- Draft until launch day. The timezone is the tenant's clock and the reason
-- there is no display_tz on the season: the league's calendar is shared, the
-- clock it is read in is not.
--
-- profile_fields turns off everything a US receipt promotion needs and a
-- Mexican pick'em does not. The trigger in 0021 enforces the other half — a
-- pickem participant without a phone or an alias cannot be written at all.
--
-- rehearsal 'anyone' lets this draft programme accept picks so the client can
-- walk it end to end before the season opens. IT COMES OFF ON LAUNCH DAY, in
-- the same edit that sets status to 'live' — leaving it on would mean a live
-- programme with a second, wider door into it.
insert into public.campaigns (org_id, slug, name, module, status, locales, config)
select o.id, 'chapa-pickem-2026', 'NFL Pick''em by Chapa', 'pickem', 'draft',
  array['es'],
  jsonb_build_object(
    'timezone', 'America/Ciudad_Juarez',
    'profile_fields', jsonb_build_object('phone', 'required', 'zip', 'off', 'state', 'off'),
    'rehearsal', 'anyone'
  )
from public.organizations o
where o.slug = 'chapa'
on conflict (slug) do update
  set name = excluded.name, config = excluded.config;

-- The three branches, verified against Chapa's public sources.
--
-- promo_weeks: 11 is the Mexico City game and 12 falls on Thanksgiving. Both
-- are full-table occasions already, which is what makes them worth doubling —
-- a double week on a dead Sunday spends the lever without moving anybody.
insert into public.pickem_programs (campaign_id, season_id, open_week, venues, promo_weeks)
select c.id, s.id, 1,
  array['Chapa Prime', 'Chapa Gómez', 'Chapa Zaragoza'],
  array[11, 12]
from public.campaigns c, public.sport_seasons s
where c.slug = 'chapa-pickem-2026' and s.league = 'nfl' and s.year = 2026
on conflict (campaign_id) do update
  set season_id = excluded.season_id,
      venues = excluded.venues,
      promo_weeks = excluded.promo_weeks;
